### ISSUE TITLE
[Delegation in detail] Typo in example calculation for last quarter block number

### ISSUE THREAD

**Issue by effofexx** [flare-foundation/docs#3]
[Delegation in detail](https://github.com/flare-foundation/docs/blob/main/docs/tutorials/delegation/delegation-in-detail.md) section [Vote power block selection](https://github.com/flare-foundation/docs/blob/main/docs/tutorials/delegation/delegation-in-detail.md#vote-power-block-selection) has a typo/error in the example calculation to determine the first block number in the fourth quarter of the epoch.

The number of blocks for each quarter of the example epoch was calculated correctly, but that value was not multiplied by 3 in the equation where it is added to the first block number for the epoch.

Documentation currently says:

> This means that 516209 blocks were mined in this epoch and the last quarter of the blocks started with the block number 2487672 + **129052** = 2874828

Documentation should say:

> This means that 516209 blocks were mined in this epoch and the last quarter of the blocks started with the block number 2487672 + **387156** = 2874828

The result of the example calculation is correct, but doesn't show the correct numbers that lead to the answer. Just a typo, but one that might become confusing for those trying to learn.

**Comment by segfaultxavi** [comment]
Agreed! Thanks for the report!
